// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StockDatum struct {
	Time             pgtype.Timestamptz
	SymbolID         string
	Open             pgtype.Numeric
	High             pgtype.Numeric
	Low              pgtype.Numeric
	Close            pgtype.Numeric
	AdjustedClose    pgtype.Numeric
	Volume           pgtype.Int8
	DividendAmount   pgtype.Numeric
	SplitCoefficient pgtype.Float8
}

type Symbol struct {
	ID       string
	Type     string
	Name     pgtype.Text
	Exchange pgtype.Text
}
