// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: stocks.sql

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateStockDataParams struct {
	Time             pgtype.Timestamptz
	SymbolID         string
	Open             pgtype.Numeric
	High             pgtype.Numeric
	Low              pgtype.Numeric
	Close            pgtype.Numeric
	AdjustedClose    pgtype.Numeric
	Volume           pgtype.Int8
	DividendAmount   pgtype.Numeric
	SplitCoefficient pgtype.Float8
}
